[build]
	command = "npm run build"
	publish = "dist"

[[headers]]
	for = "/*"

	[headers.values]
		cache-control = '''
		public,
		max-age=31536000,
		must-revalidate'''

[[headers]]
	for = "/service-worker.js"

	[headers.values]
		cache-control = '''
		max-age=0,
		no-cache,
		no-store,
		must-revalidate'''

[[headers]]
	for = "/assets/js/service-worker.js"

	[headers.values]
		cache-control = '''
		max-age=0,
		no-cache,
		no-store,
		must-revalidate'''
